# Generated by Django 5.0.6 on 2024-06-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptionlog",
            name="action",
            field=models.CharField(default="encrypt", max_length=10),
            preserve_default=False,
        ),
    ]
